import PageHero from '../components/PageHero';
import { mepItems } from '../data/siteData';
import { Check, ArrowRight } from 'lucide-react';
export default function MepDesign({onConsult}){
 const deliverables=['MEP concept & detailed drawings','Electrical load schedules','HVAC calculations & equipment selection','Plumbing sizing & schematics','Fire protection layouts','BOQ / technical specifications','Coordination drawings','Testing & commissioning support'];
 const faq=[['What is included in MEP design?','Mechanical, electrical, plumbing, fire safety and coordinated building-services documentation based on project scope.'],['Can you coordinate with architects and structural consultants?','Yes. Coordination is a core part of our workflow so clashes and service conflicts are resolved before execution.'],['Do you support execution?','Yes. Site coordination, technical clarifications, inspections and commissioning support can be added to the scope.']];
 return <><PageHero eyebrow="Engineering service" title="MEP systems designed to perform." text="Integrated mechanical, electrical and plumbing engineering for efficient, safe and future-ready buildings." image="https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1800&q=85"/>
 <section className="section"><div className="container split-grid"><div><span className="eyebrow dark">Service overview</span><h2>The invisible backbone of every high-performing building.</h2></div><div><p className="lead">We design coordinated MEP systems around the architecture — balancing comfort, energy efficiency, safety, maintainability and constructability.</p><p>From early concept loads to detailed construction documentation, every system is developed as part of one integrated building strategy.</p></div></div></section>
 <section className="section section-dark"><div className="container"><div className="center-head left"><span className="eyebrow">What’s included</span><h2>Complete MEP disciplines.</h2></div><div className="mep-grid">{mepItems.map(x=><div className="mep-card" key={x.title}><x.icon/><h3>{x.title}</h3><p>System planning, calculations, drawings, equipment strategy and interdisciplinary coordination.</p></div>)}</div></div></section>
 <section className="section"><div className="container split-grid"><div><span className="eyebrow dark">Key deliverables</span><h2>Execution-ready engineering.</h2></div><div className="deliverable-list">{deliverables.map(x=><div key={x}><Check/><span>{x}</span></div>)}</div></div></section>
 <section className="section soft-bg"><div className="container"><div className="center-head"><span className="eyebrow dark">FAQ</span><h2>Common project questions.</h2></div><div className="faq-list">{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
 <section className="cta-section"><div className="container cta-inner"><div><span className="eyebrow">MEP requirement?</span><h2>Let’s engineer it right from day one.</h2></div><button className="btn btn-light" onClick={onConsult}>Start Consultation <ArrowRight size={18}/></button></div></section></>;
}
